name: HelpUI
main: HelpUI\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

depend:
  - FormAPI

commands:
  help:
    description: View server help
    usage: "/help"
    permission: helpui.use

permissions:
  helpui.use:
    default: true
